### ISSUE TITLE
Composer require not possible

### ISSUE THREAD

**Issue by Choucky** [WandiParis/ColorPickerBundle#1]
I use EasyCorp/EasyAdminBundle with EasyAdminPlusBundle
I woult try color Type and I try to install ColorPickerBundle but I have this message :

> [InvalidArgumentException]
Could not find a matching version of package wandi/color-îcker-bundle. Check the package spelling, your version on constraint and that the package is available in a stability which matches your minimum-stability (stable).

My version of symfony 4.3

**Comment by kasou** [comment]
Hey @Choucky ,

I just added the bundle on https://packagist.org : https://packagist.org/packages/wandi/color-picker-bundle, you can now install it:

compose require wandi/color-picker-bundle

**Comment by Choucky** [comment]
Thanx I have installed this package but I have an error at the end:

> In FileLocator.php line 71:
The file "services.xml" does not exist (in: \vendor\wandi\color-picker-bundle\src\DependencyInjection/../Resources/config).

**Comment by laurent-bientz** [comment]
Hello @Choucky ,

Sorry in fact, this bundle haven't be tested, thanks to take a look on it!

I pushed [0da13e8d6e262b0096c53883f9f8a54a1924e535](https://github.com/WandiParis/ColorPickerBundle/commit/0da13e8d6e262b0096c53883f9f8a54a1924e535) to fix the typo.

Tell me if it solves the problem for u.

**Comment by Choucky** [comment]
Not really, I have other error:

> In XmlFileLoader.php line 408:
Unable to parse file "...\vendor\wandi\color-picker-bundle\src\DependencyInjection/../Resources/config\services.yaml": [ERROR 4] Start tag expected, '<' not found (in n/a - line 1, column 1)

Thanx for helps

**Comment by laurent-bientz** [comment]
ok fixed with [2ad8a4bca3bbafb63398088f2512419a9127b87b](https://github.com/WandiParis/ColorPickerBundle/commit/2ad8a4bca3bbafb63398088f2512419a9127b87b)

**Comment by Choucky** [comment]
I have a same error :

> > In XmlFileLoader.php line 408:
> > Unable to parse file "...\vendor\wandi\color-picker-bundle\src\DependencyInjection/../Resources/config\services.yaml": [ERROR 4] Start tag expected, '<' not found (in n/a - line 1, column 1)

**Comment by laurent-bientz** [comment]
did u composer update? because it's not using anymore the XmlFileLoader

**Comment by Choucky** [comment]
It's ok but use statement is forget to load class ColorExtension from namespace App\Twig\Extension:
srcApp_KenelDevDebugContainer.php

**Comment by laurent-bientz** [comment]
@Choucky I checked deeper, everything should be fine now, thanks for your patience.

composer remove then reinstall

**Comment by Choucky** [comment]
It's ok 
I remove then reinstall
It's works. Thanks
